#pragma once

// NOTE: /include/version.h is automatically generated by CMake,
// do not edit manually!
//
// Instead, edit the template in /cmake/version.h.in

#define PROJECT_VER 2.0.0
#define PROJECT_VER_MAJOR 2
#define PROJECT_VER_MINOR 0
#define PROJECT_VER_PATCH 0
